### PR TITLE
feat(playground): Support rule configuration files in json format

### PR DESCRIPTION
**Pull request by baiwusanyu-c**
close: #142

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks. But I have a few questions about the direction.
First, using JSON will split the community (which is quite small now!)
Second, we don't have any JSON based configuration documentation now. Users will be confused about what "JSON" means.
Third, having three tabs might clutter the UI, especially on mobile.

**Comment by baiwusanyu-c** [comment]
Well, having three tabs is a bit much, maybe there should be a better design on the UI.
Also, are most users more comfortable with yaml? I personally prefer json, lol. So just leave this PR here, maybe it will be useful someday

**Comment by HerringtonDarkholme** [comment]
Editing JSON by hand is not ideal. Most famous OSS projects use YAML/TOML for complicated configuration (K8s).

As a hobby project, I don't think I have enough bandwidth to support another documentation for JSON. 
Sorry about that.

**Comment by baiwusanyu-c** [comment]
Ok, I get it, since I'm more of using ts/js for rule file input, I'll close this pr

**Comment by HerringtonDarkholme** [comment]
Just a reminder, YAML is actually a superset of JSON. So you can already use the playground with JSON.

Example
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwiY29uZmlnIjoicnVsZToge1xuICBcInBhdHRlcm5cIjogXCJjb25zb2xlLmxvZygkQSlcIixcbiAgICAgIFwiaGFzXCI6IHtcbiAgICAgICAgXCJraW5kXCI6IFwic3RyaW5nXCIsXG4gICAgICAgIFwic3RvcEJ5XCI6IFwiZW5kXCJcbiAgICAgIH1cbn0iLCJzb3VyY2UiOiIvLyBjb25zb2xlLmxvZygpIHdpbGwgYmUgbWF0Y2hlZCBieSBwYXR0ZXJuIVxuLy8gY2xpY2sgZGlmZiB0YWIgdG8gc2VlIHJld3JpdGUuXG5cbmZ1bmN0aW9uIHRyeUFzdEdyZXAoKSB7XG4gIGNvbnNvbGUubG9nKCdtYXRjaGVkIGluIG1ldGF2YXIhJylcbn1cblxuY29uc3QgbXVsdGlMaW5lRXhwcmVzc2lvbiA9XG4gIGNvbnNvbGVcbiAgIC5sb2coJ0Fsc28gbWF0Y2hlZCEnKVxuXG5pZiAodHJ1ZSkge1xuICBjb25zdCBub3RUaGlzID0gJ2NvbnNvbGUubG9nKFwibm90IG1lXCIpJ1xufSBlbHNlIHtcbiAgY29uc29sZS5kZWJ1ZygnbWF0Y2hlZCBieSBZQU1MJylcbn0ifQ==

**Comment by baiwusanyu-c** [comment]
thank ！🙏

**Pull request closed without merging**
